### ISSUE TITLE
.exe won't start

### ISSUE THREAD

**Issue by NerdWins** [flacostec/PoEDirectionHelper#1] opened 2018-11-25 13:37 UTC
The Programm won't start on my pc.
Just downloaded the version 3 zip and unziped it on my Desktop.

Executing the .exe does nothing. There is not even a process popping up in my task manager.

It doesn't matter rather i start it before or while the Game is running.
I tried executing it on the coast and in the city then entering the coast.

Admin mode and kompatibility mode won't fix the problem.
Im running the game with steam and on Windows 10.

**Comment by KyleTilton** [comment] 2018-11-26 20:04
I am having this same issue. Windows 10, steam also.

**Comment by Doctah** [comment] 2018-11-26 23:34
It's most likely due to the fact the program only detects standalone installs, not ones on Steam. The program will silently fail and close. Would probably be best handled by allowing users to input their own directory if none are found automatically.

**Comment by flacostec** [comment] 2018-11-26 23:48
I think I've fixed it. You can now configure the client.txt location within configuration.json 

[New version](https://github.com/flacostec/PoEDirectionHelper/releases/tag/4.0)

Let me know if the problem is solved.

**Comment by KyleTilton** [comment] 2018-11-27 22:18
I ended up installing the stand alone client which did fix it. I can't test to see if it is fixed on the steam version now though.

**Comment by NerdWins** [comment] 2018-11-28 09:46
After changing the Path in the config file to "c:\\program files ....", the steam version works with my steam client.  Thanks for the quick fix.

**Closed** 2018-11-28 13:36 UTC
